[package]
name = "assembler"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
customasm = "0.13.5"
wasm-bindgen = { version = "0.2.92" }
fs = { git = "https://github.com/ICMC-IDE/fs.git" }

[profile.release]
panic = "abort"
lto = "fat"
opt-level = 3
